version: '3'
services:
  # https://stackoverflow.com/a/35895156/1886079
  # init:
  #  build: .
  #  command: ["node", "init.js"]
  api:
    build:
      context: ../
      dockerfile: example/Dockerfile
    ports: 
      - "8081:8081"
    # depends_on:
    #   - "init"
    restart: always
    command: ["node", "example/server.js", "api"]
  web:
    build:
      context: ../
      dockerfile: example/Dockerfile
    ports: 
      - "8080:8080"
    restart: always
    depends_on:
      - "api"
    command: ["node", "example/server.js", "web"]
  #nginx:
  #  image: nginx
  #  restart: always
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - config/nginx.conf:/etc/nginx/nginx.conf:ro
  #    - config/logs/nginx:/var/logs
  #  depends_on:
  #    - "web"
  #    - "api"