version: '3'
services:
  # https://stackoverflow.com/a/35895156/1886079
  init:
    build: .
    command: ["node", "init.js"]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/stackdriver.json
  # https://docs.docker.com/compose/gettingstarted/#step-5-edit-the-compose-file-to-add-a-bind-mount
  api:
    build: .
    ports: 
      - "8081:8081"
    depends_on:
      - "init"
    restart: always
    command: ["npm", "run", "start-api"]
    # https://node-postgres.com/features/connecting
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/stackdriver.json
  web:
    build: .
    restart: always
    depends_on:
      - "api"
    command: ["npm", "run", "start-web"]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/stackdriver.json
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /dmdashboard/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /dmdashboard/nginx/logs:/var/logs
    depends_on:
      - "web"
      - "api"


      # PGPASSWORD=cva7efca3ameues7 psql -U dashron2 -h dashron-do-user-1018600-0.db.ondigitalocean.com -p 25060 -d dashron2 <local-pg-dump-path> 