FROM nginx

COPY tsExample/config/nginx.conf /etc/nginx/nginx.conf
COPY tsExample/config/certificate.pem /etc/nginx/certificate.pem
COPY tsExample/config/privatekey.pem /etc/nginx/privatekey.pem
COPY tsExample/static /web/static