# https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
FROM node:13

# Create app directory
WORKDIR /code

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

# Ensure we're using the most recent version of roads starter in this example
COPY . ./tsExample/node_modules/roads-starter