version: '3'
services:
  # https://stackoverflow.com/a/35895156/1886079
  # init:
  #  build: .
  #  command: ["node", "init.js"]
  api:
    build:
      context: ../
      dockerfile: jsExample/Dockerfile-node
    # depends_on:
    #   - "init"
    restart: always
    environment: 
      ROADS_ENV: "docker"
    command: ["node", "jsExample/server.js", "api"]
  web:
    build:
      context: ../
      dockerfile: jsExample/Dockerfile-node
    restart: always
    environment: 
      ROADS_ENV: "docker"
    depends_on:
      - "api"
    command: ["node", "jsExample/server.js", "web"]
  nginx:
    build:
      context: ../
      dockerfile: jsExample/Dockerfile-nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - "web"
      - "api"